### ISSUE TITLE
link to online documentation is broken

### ISSUE THREAD

**Issue by jmeyer1980** [rickycorte/Unity5-Build-System#3]
Please fix this.

**Comment by rickycorte** [comment]
At the moment, you can find them here:
https://www.rickycorte.com/BuildSystem/manual/
https://www.rickycorte.com/BuildSystem/docs/

Since the project is a bit old and not maintained anymore, it's better to use the offline copy of the documentation and manual bundled in the project. You can find them here:
https://github.com/rickycorte/Unity5-Build-System/blob/master/Assets/BuildSystem/Docs/docs.zip

**Comment by jmeyer1980** [comment]
Thanks. There is an issue with the outline effect script, but that's not yours, I believe you included that package in this one and it's simply a matter of replacing every occurance of "VR" with "XR" there's like six or seven of them.

You said this is no longer supported and, indeed, has been deprecated on the asset store... so obvs don't worry about it.

**Comment by rickycorte** [comment]
The outline effect is old and has been tested up to Unity 5. In recent versions of Unity, the effect is broken but it should not be really hard to remove it or replace it with something else.
